env_file:
  - path: ./.env
    required: true

services:
  postgres:
    container_name: postgres-sql
    image: postgres:15.6
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.7
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-sql:5432/student-space
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8888:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - postgres

  # next-frontend:
  #   container_name: frontend
  #   image: ghcr.io/adrianhuszka/student-space/app:latest
  #   pull_policy: always
  #   restart: unless-stopped
  #   ports:
  #     - "80:3000"
  #   environment:
  #     BACKEND_URL: http://138.3.248.186:8080
  #     NEXTAUTH_URL: http://138.3.248.186
  #     NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  #     KEYCLOAK_URL: ${KEYCLOAK_URL}
  #     KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #     KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
  #     KEYCLOAK_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
  #     KEYCLOAK_SESSION_END_URL: ${KEYCLOAK_SESSION_END_URL}
  #     KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
  #     KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

  redis:
    container_name: redis
    image: redis:7.2.4
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: unless-stopped

  discovery-service:
    image: ghcr.io/adrianhuszka/student-space-backend/discovery-service:0.1
    platform: linux/arm64
    container_name: discovery-service
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      - redis

  gateway-service:
    image: ghcr.io/adrianhuszka/student-space-backend/api-gateway:0.1
    platform: linux/arm64
    container_name: gateway-service
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery-service
      - keycloak

  administration-service:
    image: ghcr.io/adrianhuszka/student-space-backend/administration-service:0.1
    platform: linux/arm64
    container_name: administration-service
    pull_policy: always
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_BACKEND_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_BACKEND_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    depends_on:
      - postgres
      - keycloak
      - redis
      - discovery-service
      - gateway-service

  scene-service:
    image: ghcr.io/adrianhuszka/student-space-backend/scene-service:0.1
    platform: linux/arm64
    container_name: scene-service
    pull_policy: always
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - postgres
      - keycloak
      - redis
      - discovery-service
      - gateway-service

  forum-service:
    image: ghcr.io/adrianhuszka/student-space-backend/forum-service:0.1
    platform: linux/arm64
    container_name: forum-service
    pull_policy: always
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - postgres
      - keycloak
      - redis
      - discovery-service
      - gateway-service

volumes:
  pgdata:
  pgadmin:
  redis:
    driver: local
