version: "3.9"

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    restart: unless-stopped
